// Code generated by reset. DO NOT EDIT.

package handler

import (
	gzip "compress/gzip"
	sql "database/sql"

	config "github.com/lxmp7p/yaGo-url-shortener/internal/config"
	logger "github.com/lxmp7p/yaGo-url-shortener/internal/logger"
	service "github.com/lxmp7p/yaGo-url-shortener/internal/service"
	logrus "github.com/sirupsen/logrus"
)

func (s *Handler) Reset() {
	if s.Service != nil {
		*s.Service = service.ShortenerService{}
	}
}

func (s *App) Reset() {
	s.Config = config.Config{}
	if s.Logger != nil {
		*s.Logger = logrus.Logger{}
	}
	if s.Database != nil {
		*s.Database = sql.DB{}
	}
	if s.Dispatcher != nil {
		*s.Dispatcher = logger.Dispatcher{}
	}
}

func (s *logRequest) Reset() {
	s.URI = ""
	s.Method = ""
	s.StatusCode = 0
	s.ResponseSize = 0
}

func (s *loggerResponseWriter) Reset() {
	s.size = 0
	s.statusCode = 0
}

func (s *compressResponseWriter) Reset() {
	if s.Writer != nil {
		*s.Writer = gzip.Writer{}
	}
}
