// Code generated by reset. DO NOT EDIT.

package repository

import (
	sql "database/sql"
	os "os"
	sync "sync"
)

func (s *Cache) Reset() {
	clear(s.URLCache)
	s.mu = sync.RWMutex{}
	s.filename = ""
	if s.file != nil {
		*s.file = os.File{}
	}
}

func (s *URL) Reset() {
	s.Original = ""
	s.Short = ""
	s.UserID = ""
	s.DeletedFlag = false
}

func (s *DatabaseCache) Reset() {
	if s.db != nil {
		*s.db = sql.DB{}
	}
}

func (s *URLError) Reset() {
	s.Short = ""
}
