// Code generated by reset. DO NOT EDIT.

package logger

import (
	os "os"
	sync "sync"

	retryablehttp "github.com/hashicorp/go-retryablehttp"
)

func (s *Dispatcher) Reset() {
	s.mu = sync.RWMutex{}
	s.observers = s.observers[:0]
}

func (s *FileObserver) Reset() {
	if s.File != nil {
		*s.File = os.File{}
	}
	s.mu = sync.Mutex{}
}

func (s *HTTPObserver) Reset() {
	s.url = ""
	if s.client != nil {
		*s.client = retryablehttp.Client{}
	}
}
