// Code generated by reset. DO NOT EDIT.

package service

import (
	sql "database/sql"

	config "github.com/lxmp7p/yaGo-url-shortener/internal/config"
	logger "github.com/lxmp7p/yaGo-url-shortener/internal/logger"
	logrus "github.com/sirupsen/logrus"
)

func (s *DeleteTask) Reset() {
	s.UserID = ""
	s.IDs = s.IDs[:0]
}

func (s *ShortenerService) Reset() {
	s.Config = config.Config{}
	s.Logger = logrus.Logger{}
	if s.Database != nil {
		*s.Database = sql.DB{}
	}
	s.secret = s.secret[:0]
	if s.Dispatcher != nil {
		*s.Dispatcher = logger.Dispatcher{}
	}
}

func (s *ShortenRequest) Reset() {
	s.URL = ""
}

func (s *ShortenResponse) Reset() {
	s.Result = ""
}

func (s *Original) Reset() {
	s.ID = ""
	s.OriginalURL = ""
}

func (s *Shorten) Reset() {
	s.ID = ""
	s.ShortURL = ""
}
