// Code generated by reset. DO NOT EDIT.

package config

func (s *Config) Reset() {
	s.Addr = ""
	s.ResultAddr = ""
	s.FileStoragePath = ""
	s.DatabaseDsn = ""
	s.FileLogging = LoggerInfo{}
	s.RemoteLogging = LoggerInfo{}
}

func (s *LoggerInfo) Reset() {
	s.Path = ""
	s.Enable = false
}
