package generator

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"sort"

	"golang.org/x/tools/go/packages"
	"golang.org/x/tools/imports"
)

type StructInfo struct {
	Name string
	Type *types.Struct
}

func Run(root string) error {
	cfg := &packages.Config{
		Mode: packages.NeedName |
			packages.NeedSyntax |
			packages.NeedTypes |
			packages.NeedTypesInfo |
			packages.NeedCompiledGoFiles,
		Dir: root,
	}

	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		return err
	}

	getStruct(pkgs)

	return nil
}

func getStruct(pkgs []*packages.Package) {
	for _, pkg := range pkgs {
		var structs []StructInfo

		for _, file := range pkg.Syntax {
			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE || !hasGenerateReset(genDecl.Doc) {
					continue
				}

				for _, spec := range genDecl.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}

					if _, ok := typeSpec.Type.(*ast.StructType); !ok {
						continue
					}

					if info, ok := getStructInfo(pkg, typeSpec); ok {
						structs = append(structs, info)
					}
				}
			}
		}

		if len(structs) > 0 {
			generateFileCode(pkg, structs)
		}
	}
}

func hasGenerateReset(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}

	for _, comment := range doc.List {
		if comment.Text == "// generate:reset" {
			return true
		}
	}

	return false
}

func getStructInfo(pkg *packages.Package, typeSpec *ast.TypeSpec) (StructInfo, bool) {
	obj := pkg.Types.Scope().Lookup(typeSpec.Name.Name)
	if obj == nil {
		return StructInfo{}, false
	}

	named, ok := obj.Type().(*types.Named)
	if !ok {
		return StructInfo{}, false

	}

	strct, ok := named.Underlying().(*types.Struct)
	if !ok {
		return StructInfo{}, false

	}

	return StructInfo{
		Name: typeSpec.Name.Name,
		Type: strct,
	}, true
}

func generateFileCode(pkg *packages.Package, structs []StructInfo) {
	usedImports := map[string]string{}
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "// Code generated by reset. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkg.Name)

	var methodsBuf bytes.Buffer

	for _, s := range structs {
		fmt.Fprintf(&methodsBuf, "func (s *%s) Reset() {\n", s.Name)

		st := s.Type
		for i := 0; i < st.NumFields(); i++ {
			field := st.Field(i)
			emitReset(&methodsBuf, "s."+field.Name(), field.Type(), usedImports, pkg.PkgPath)
		}

		fmt.Fprintf(&methodsBuf, "}\n\n")
	}

	if len(usedImports) > 0 {
		fmt.Fprintf(&buf, "import (\n")
		keys := make([]string, 0, len(usedImports))
		for k := range usedImports {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		for _, path := range keys {
			if path == pkg.PkgPath {
				continue
			}
			alias := usedImports[path]
			if alias == "" || alias == pkg.Name {
				fmt.Fprintf(&buf, "\t\"%s\"\n", path)
			} else {
				fmt.Fprintf(&buf, "\t%s \"%s\"\n", alias, path)
			}
		}
		fmt.Fprintf(&buf, ")\n\n")
	}

	buf.Write(methodsBuf.Bytes())

	src, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Println("format error:", err)
		return
	}

	cleaned, err := processWithGoImports(src)
	if err == nil {
		src = cleaned
	} else {
		fmt.Println("goimports not available, using gofmt only")
	}

	dir := filepath.Dir(pkg.CompiledGoFiles[0])
	err = os.WriteFile(filepath.Join(dir, "reset.gen.go"), src, 0644)
	if err != nil {
		fmt.Println("write error:", err)
	}
}

func emitReset(buf *bytes.Buffer, expr string, t types.Type, imports map[string]string, currentPkgPath string) {
	qualifier := func(p *types.Package) string {
		if p == nil || p.Path() == currentPkgPath {
			return ""
		}
		return p.Name()
	}

	switch v := t.(type) {

	case *types.Basic:
		switch {
		case v.Info()&types.IsString != 0:
			fmt.Fprintf(buf, "\t%s = \"\"\n", expr)
		case v.Info()&types.IsBoolean != 0:
			fmt.Fprintf(buf, "\t%s = false\n", expr)
		default:
			fmt.Fprintf(buf, "\t%s = 0\n", expr)
		}

	case *types.Slice:
		fmt.Fprintf(buf, "\t%s = %s[:0]\n", expr, expr)

	case *types.Map:
		fmt.Fprintf(buf, "\tclear(%s)\n", expr)

	case *types.Pointer:
		elem := v.Elem()
		fmt.Fprintf(buf, "\tif %s != nil {\n", expr)

		switch e := elem.(type) {
		case *types.Named:
			if shouldImport(e, currentPkgPath) {
				addImportIfNeeded(imports, e, currentPkgPath)
			}
			if hasReset(e) {
				fmt.Fprintf(buf, "\t\t%s.Reset()\n", expr)
			} else {
				fmt.Fprintf(buf, "\t\t*%s = %s{}\n", expr, types.TypeString(e, qualifier))
			}
		default:
			emitReset(buf, "*"+expr, elem, imports, currentPkgPath)
		}
		fmt.Fprintf(buf, "\t}\n")

	case *types.Named:
		if shouldImport(v, currentPkgPath) {
			addImportIfNeeded(imports, v, currentPkgPath)
		}
		if _, ok := v.Underlying().(*types.Struct); ok {
			if hasReset(v) {
				fmt.Fprintf(buf, "\t%s.Reset()\n", expr)
			} else {
				fmt.Fprintf(buf, "\t%s = %s{}\n", expr, types.TypeString(v, qualifier))
			}
		}
	}
}

func shouldImport(t *types.Named, currentPkgPath string) bool {
	if t == nil {
		return false
	}
	pkg := t.Obj().Pkg()
	if pkg == nil || pkg.Path() == "" || pkg.Path() == currentPkgPath {
		return false
	}
	return true
}

func addImportIfNeeded(imports map[string]string, t *types.Named, currentPkgPath string) {
	if pkg := t.Obj().Pkg(); pkg != nil && pkg.Path() != "" && pkg.Path() != currentPkgPath {
		imports[pkg.Path()] = pkg.Name()
	}
}

func hasReset(t types.Type) bool {
	ms := types.NewMethodSet(types.NewPointer(t))
	for i := 0; i < ms.Len(); i++ {
		if ms.At(i).Obj().Name() == "Reset" {
			return true
		}
	}
	return false
}

func processWithGoImports(src []byte) ([]byte, error) {
	opts := &imports.Options{
		TabWidth:   8,
		TabIndent:  false,
		Comments:   true,
		Fragment:   true,
		FormatOnly: false,
	}

	return imports.Process("reset.gen.go", src, opts)
}
